[Sat Mar 23 11:46:36 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14139): Exception occurred processing WSGI script '/vagrant/app/2-dictionary/main.py'.
[Sat Mar 23 11:46:36 2013] [error] [client 192.168.33.1] TypeError: sequence of byte string values expected, value of type list found
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14139, process='', application='www.example.com|/2-dictionary/main.py'): Failed to parse WSGI script file '/vagrant/app/2-dictionary/main.py'.
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14139): Exception occurred processing WSGI script '/vagrant/app/2-dictionary/main.py'.
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1]   File "/vagrant/app/2-dictionary/main.py", line 14
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1]     content_length = 0
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1]                      ^
[Sat Mar 23 11:49:24 2013] [error] [client 192.168.33.1] IndentationError: unindent does not match any outer indentation level
[Sat Mar 23 12:08:41 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14138): Exception occurred processing WSGI script '/vagrant/app/3-get/main.py'.
[Sat Mar 23 12:08:41 2013] [error] [client 192.168.33.1] Traceback (most recent call last):
[Sat Mar 23 12:08:41 2013] [error] [client 192.168.33.1]   File "/vagrant/app/3-get/main.py", line 25, in application
[Sat Mar 23 12:08:41 2013] [error] [client 192.168.33.1]     d = parse_qs(environ['QUERY_STRING'])
[Sat Mar 23 12:08:41 2013] [error] [client 192.168.33.1] NameError: global name 'parse_qs' is not defined
[Sat Mar 23 12:08:52 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14138): Exception occurred processing WSGI script '/vagrant/app/3-get/main.py'.
[Sat Mar 23 12:08:52 2013] [error] [client 192.168.33.1] RuntimeError: response has not been started
[Sat Mar 23 12:11:14 2013] [error] [client 192.168.33.1] mod_wsgi (pid=14138): Exception occurred processing WSGI script '/vagrant/app/3-get/main.py'.
[Sat Mar 23 12:11:14 2013] [error] [client 192.168.33.1] Traceback (most recent call last):
[Sat Mar 23 12:11:14 2013] [error] [client 192.168.33.1]   File "/vagrant/app/3-get/main.py", line 26, in application
[Sat Mar 23 12:11:14 2013] [error] [client 192.168.33.1]     d = parse_qs(environ['QUERY_STRING'])
[Sat Mar 23 12:11:14 2013] [error] [client 192.168.33.1] NameError: global name 'parse_qs' is not defined
[Sat Mar 23 12:12:22 2013] [error] [client 192.168.33.1] Target WSGI script not found or unable to stat: /vagrant/app/3-get/parsing_get.wsgi, referer: http://192.168.33.13/3-get/main.py
